= First look at Firecracker
:toc:

= Chapter 1: What is Firecracker

**Slides**

. What is Firecracker?
. Benefits of Firecracker

= Chapter 2: Firecracker Design

**Slides**

. Firecracker Design Principles
. Firecracker Design

= Chapter 3: Firecracker and Lambda

**Slides**

= Chapter 4: Firecracker and Fargate (TBD)

**Slides**

= Chapter 5: Getting Started with Firecracker

**Prep Work**

. Create an `m3.metal` instance using Amazon Linux 2 on EC2. 
. Clone and build `firectl`:

    sudo yum install -y git
    git clone https://github.com/firecracker-microvm/firectl
    sudo amazon-linux-extras install -y golang1.11
    cd firectl
    make

**Code**

. Firecracker uses KVM and needs read/write access that can be granted as shown below:

    sudo setfacl -m u:${USER}:rw /dev/kvm

. Download the Firecracker binary:

    curl -LOJ https://github.com/firecracker-microvm/firecracker/releases/download/v0.15.0/firecracker-v0.15.0
    chmod +x firecracker-v0.15.0
    sudo mv firecracker-v0.15.0 /usr/local/bin/firecracker

. Download kernel and root filesystem:

    curl -fsSL -o hello-vmlinux.bin https://s3.amazonaws.com/spec.ccfc.min/img/hello/kernel/hello-vmlinux.bin
    curl -fsSL -o hello-rootfs.ext4 https://s3.amazonaws.com/spec.ccfc.min/img/hello/fsfiles/hello-rootfs.ext4

. Create microVM:

    ./firectl \
      --kernel=hello-vmlinux.bin \
      --root-drive=hello-rootfs.ext4

. Terminal 1 shows a login prompt:

    Welcome to Alpine Linux 3.8
    Kernel 4.14.55-84.37.amzn2.x86_64 on an x86_64 (ttyS0)
    localhost login:

. Log in as `root` with password `root`
. Show the filesystem using `ls /`

= Chapter 6: Access the microVM using REST API:

. In a new terminal, query the microVM:

    $ curl --unix-socket ~/.firecracker.sock-* http://localhost/
    {"id":"anonymous-instance","state":"Running","vmm_version":"0.15.0"}

. Get more details about the VM:
+
    $ curl --unix-socket ~/.firecracker.sock-* http://localhost/machine-config
    { "vcpu_count": 1, "mem_size_mib": 512,  "ht_enabled": true,  "cpu_template": "Uninitialized" }
+
Show the vCPU and memory size.
+
. Try to update the vCPU:

    $ curl --unix-socket ~/.firecracker.sock-* -X PUT http://localhost/machine-config -d '{ "vcpu_count": 2}'
    {
    "fault_message": "The update operation is not allowed after boot."
    }

. Shutdown the microVM:

    curl --unix-socket ~/.firecracker.sock-* -X PUT http://localhost/actions -d '{ "action_type": "SendCtrlAltDel" }'

. Start again:

    ./firectl \
      --kernel=hello-vmlinux.bin \
      --root-drive=hello-rootfs.ext4

. Terminate the microVM using `reboot`

= Chapter 7: Starting 1000 microVMs using Firecracker

**Prep Work*

. Create an `i3.metal` instance using AL2
. Update the machine:

    sudo yum update -y
    sudo yum install -y git python3

**Code**

. Install:

    git clone https://github.com/firecracker-microvm/firecracker-demo

. Setup:

    sudo tee -a /etc/security/limits.conf <<EOL
    ec2-user soft nproc 16384
    ec2-user hard nproc 16384
    EOL
    sudo setfacl -m u:${USER}:rw /dev/kvm

. In terminal 1:

    cd firecracker-demo
    TERM='xterm-256color'
    python3 microvm-tiles.py

. In terminal 2:

    cd firecracker-demo
    sudo ./0.initial-setup.sh 4000
    ./parallel-start-many.sh 0 4000 6

= Chapter 8: Firecracker and Container Integration

**Slides**

. Firecracker and Kata Containers
. Firecracker and Containerd

= Chapter 9: Next Steps with Firecracker



